In [10]:
import numpy as np
np_arr_1d_1=np.array([10,20,30,40])
np_arr_1d_2=np.array([10,20,30,40])
print(np_arr_1d_1)
print(np.add(np_arr_1d_1,np_arr_1d_2))
np_array_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np_array_2d)

[10 20 30 40]
[20 40 60 80]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
import numpy as np
np_arr_1d_1=[1,2,3,4,5]
x=np.array(np_arr_1d_1)
# print(x)
type(x)
type(np_arr_1d_1)

list

In [29]:
import numpy as np
print(np.zeros((10,10)))

print(np.ones(3))

print(np.full((2,3),4))


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[1. 1. 1.]
[[4 4 4]
 [4 4 4]]


In [35]:
import numpy as np
print(np.arange(4))
print(np.arange(2,7,2))


[0 1 2 3]
[2 4 6]


In [38]:
import numpy as np
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [43]:
import numpy as np
mt=np.arange(3,42,1)
print(np.shape(mt))
print(mt.shape)

(39,)
(39,)


In [72]:
from math import ceil
import numpy as np
mt=np.array([[3,4,5,6],[3.65,4,5,1]])
print(mt)
print(mt.size)
print(mt.ndim)
print(mt.dtype)
xx=np.ceil(mt)
print(xx.astype(int))

[[3.   4.   5.   6.  ]
 [3.65 4.   5.   1.  ]]
8
2
float64
[[3 4 5 6]
 [4 4 5 1]]


In [ ]:
import numpy as np
mt=np.array([[3,3,53,6],[5,7,8,9]])
print(mt+2)
print(mt**2)
print(mt-2)


[[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]
[[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [78]:
import numpy as np
mt=np.full((4,4),3)
print(np.sum(mt))
print(np.average(mt))
print(np.mean(mt))
print(np.std(mt))
print(np.var(mt))
print(np.max(mt))


48
3.0
3.0
0.0
0.0
3


In [ ]:
import numpy as np
mt=np.array([3,4,6,5,6,7,8,6,5,76])
print(mt[3])
print(mt[[2,3,4]])
print(mt[1:6:2])
print(mt[-7:-2])
print(mt[::-1])
print(mt[mt%2==0])



5
[6 5 6]
[4 5 7]
[5 6 7 8 6]
[76  5  6  8  7  6  5  6  4  3]
[ 4  6  6  8  6 76]


In [112]:
import numpy as np
mt=np.array([3,4,6,5,6,7,8,6,5,76])
print(mt.ndim)

print(mt)
print(mt.reshape(5,2))

print(mt.ndim)
mt2=mt.reshape(5,2)

mt2[0]=999
print(mt2)
print(mt)
mt.ndim


1
[ 3  4  6  5  6  7  8  6  5 76]
[[ 3  4]
 [ 6  5]
 [ 6  7]
 [ 8  6]
 [ 5 76]]
1
[[999 999]
 [  6   5]
 [  6   7]
 [  8   6]
 [  5  76]]
[999 999   6   5   6   7   8   6   5  76]


1

In [137]:
import numpy as np
mt2=np.ones((2,2,2))
mt1=mt2.ravel()
print(mt2)
print("hio")
print(mt1)
mt1[2]=333
print(mt2)
print(mt1)
mt2=np.ones((2,2,2))

mt1=mt2.flatten()
mt1[2]=333
print(mt2)
print(mt1)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
hio
[1. 1. 1. 1. 1. 1. 1. 1.]
[[[  1.   1.]
  [333.   1.]]

 [[  1.   1.]
  [  1.   1.]]]
[  1.   1. 333.   1.   1.   1.   1.   1.]
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
[  1.   1. 333.   1.   1.   1.   1.   1.]


In [164]:
import numpy as np
mt=np.zeros((3,3))
mt=mt.astype(int)
print(mt.dtype)
mt=np.insert(mt,2,5)
print(mt)

mt=np.zeros((3,3))

mt=np.insert(mt,[2,3],5,axis=0)
print(mt)

mt=np.zeros((3,3))

mt=np.insert(mt,[2,3],5,axis=1)
print(mt)

mt=np.append(mt,[3,5,6])
print(mt.reshape(9,2))

int32
[0 0 5 0 0 0 0 0 0 0]
[[0. 0. 0.]
 [0. 0. 0.]
 [5. 5. 5.]
 [0. 0. 0.]
 [5. 5. 5.]]
[[0. 0. 5. 0. 5.]
 [0. 0. 5. 0. 5.]
 [0. 0. 5. 0. 5.]]
[[0. 0.]
 [5. 0.]
 [5. 0.]
 [0. 5.]
 [0. 5.]
 [0. 0.]
 [5. 0.]
 [5. 3.]
 [5. 6.]]


In [175]:
import numpy as np
mt1=np.array([2,3,4,5])
mt2=np.array([7,32,9,52])
arr=np.concatenate((mt1,mt2))
print(arr)

arr2=np.array([3,4,5])
print(np.delete(arr2,[0]))

arr2=np.array([[3,4,5],[6,7,8]])
np.delete(arr2,[0],axis=1)

[ 2  3  4  5  7 32  9 52]
[4 5]


array([[4, 5],
       [7, 8]])

In [179]:
import numpy as np
mt1=np.array([2,3,4,5])
mt2=np.array([7,32,9,52])

print(np.vstack((mt1,mt2)))
print(np.hstack((mt1,mt2)))

[[ 2  3  4  5]
 [ 7 32  9 52]]
[ 2  3  4  5  7 32  9 52]


In [196]:
import numpy as np
mt1=np.array([2,3,7,8,5,3,4,5])
print(np.split(mt1,4))
print(mt1)
x,y=np.hsplit(mt1,2)
print(mt1)
print(f"x={x},y={y}")
mt1=mt1.reshape(4,2)
print(mt1)

print(np.vsplit(mt1,4))

[array([2, 3]), array([7, 8]), array([5, 3]), array([4, 5])]
[2 3 7 8 5 3 4 5]
[2 3 7 8 5 3 4 5]
x=[2 3 7 8],y=[5 3 4 5]
[[2 3]
 [7 8]
 [5 3]
 [4 5]]
[array([[2, 3]]), array([[7, 8]]), array([[5, 3]]), array([[4, 5]])]


In [203]:
import numpy as np
mt1=np.array([[2,3,7,8],[5,3,4,5]])
mt2=np.array([2])
print(mt1+mt2)
mt2=np.array([[2],[3]])
print(mt1+mt2)
mt2=np.array([2,3])
print(mt1+mt2)


[[ 4  5  9 10]
 [ 7  5  6  7]]
[[ 4  5  9 10]
 [ 8  6  7  8]]


ValueError: operands could not be broadcast together with shapes (2,4) (2,) 

In [223]:
import timeit
a = [1, 2, 3, 4, 5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,6,6,6,6,6,6,6,76,7,7,7,7,7,7,7,7,77,7,7,7,7,7]
b = [1, 2, 3, 4, 6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,7,7,7,7,7,7,34,5,5,5,5,5,4,2,2,2,2,2,2,2,2,2]

print(timeit.timeit('[x ** y for x, y in zip(a, b)]', globals=globals(), number=10000))

import numpy as np
a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 3, 4])
print(timeit.timeit('a ** b', globals=globals(), number=10000))

0.08853550005005673
0.003599800053052604


In [15]:
import numpy as np
mt = np.array([1, 2, np.nan, 4, 5, np.nan, 7])
null_idx = np.where(np.isnan(mt))[0].tolist()
notnullmt = np.nan_to_num(mt, nan=1)
print(null_idx)


[2, 5]


In [18]:
import numpy as np
mt = np.array([1, 2, np.inf, 4, 5, -np.inf, 7])
print(np.isinf(mt))
new_arr=np.nan_to_num(mt,posinf=1000,neginf=-1000)
new_arr

[False False  True False False  True False]


array([    1.,     2.,  1000.,     4.,     5., -1000.,     7.])

In [20]:
import numpy as np

# Example usage of numpy.linalg module

# Create a 2x2 matrix
A = np.array([[1, 2], [3, 4]])

# Compute the determinant
det_A = np.linalg.det(A)
print("Determinant of A:", det_A)

# Compute the inverse
inv_A = np.linalg.inv(A)
print("Inverse of A:\n", inv_A)

# Compute the eigenvalues and eigenvectors
eigvals, eigvecs = np.linalg.eig(A)
print("Eigenvalues of A:", eigvals)
print("Eigenvectors of A:\n", eigvecs)

# Solve a linear system Ax = b
b = np.array([5, 6])
x = np.linalg.solve(A, b)
print("Solution x of Ax = b:", x)

# Compute the singular value decomposition
U, s, Vh = np.linalg.svd(A)
print("Singular values of A:", s)


Determinant of A: -2.0000000000000004
Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues of A: [-0.37228132  5.37228132]
Eigenvectors of A:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
Solution x of Ax = b: [-4.   4.5]
Singular values of A: [5.4649857  0.36596619]
